## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [23]:
import os
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [3]:
# 設定 data_path
dir_data = './data/'

In [4]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [47]:
t = app_train.shape
(r, c) = t
(r, c)

(307511, 122)

#### 列出所有欄位

In [38]:
app_train.head(r)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307485,456229,0,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307486,456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307496,456240,0,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

#### 截取部分資料

In [61]:
app_train.loc[10000:10050]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
10000,111634,0,Cash loans,F,N,N,0,225000.0,675000.0,19737.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10001,111635,0,Cash loans,F,N,Y,0,270000.0,799299.0,37170.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
10002,111636,0,Cash loans,M,Y,N,0,315000.0,450000.0,53536.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10003,111637,0,Cash loans,F,N,Y,3,189000.0,450000.0,23692.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10004,111638,0,Cash loans,F,N,N,0,67500.0,450000.0,23656.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
10005,111639,0,Cash loans,F,N,Y,0,144000.0,254700.0,14620.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
10006,111640,1,Cash loans,M,N,Y,1,247500.0,204768.0,13815.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
10007,111642,0,Cash loans,M,N,Y,1,270000.0,976711.5,38866.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
10008,111643,0,Cash loans,F,Y,Y,0,157500.0,573628.5,29416.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
10009,111644,1,Cash loans,M,Y,Y,0,202500.0,269982.0,27792.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
10010,111645,0,Cash loans,F,N,N,0,202500.0,327024.0,21289.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
10011,111647,0,Revolving loans,F,N,Y,1,90000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
10012,111648,0,Cash loans,F,N,Y,0,135000.0,536917.5,30109.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10013,111649,1,Cash loans,F,Y,Y,0,135000.0,225000.0,26833.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
10014,111650,0,Cash loans,M,Y,Y,0,180000.0,288873.0,18459.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
10015,111651,0,Cash loans,F,N,N,0,135000.0,219042.0,24844.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10016,111653,0,Cash loans,M,Y,N,0,450000.0,2013840.0,53122.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
10017,111654,0,Cash loans,M,Y,N,0,180000.0,1515415.5,41800.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10018,111655,0,Cash loans,F,N,Y,1,135000.0,1350000.0,39474.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10019,111656,1,Cash loans,F,N,Y,0,202500.0,611950.5,48478.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
10020,111658,0,Revolving loans,M,Y,Y,1,135000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
10021,111659,0,Cash loans,F,N,N,1,112500.0,450000.0,30204.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
10022,111660,0,Revolving loans,F,N,Y,0,81000.0,225000.0,11250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10023,111661,0,Cash loans,M,N,Y,1,76500.0,127350.0,13842.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
10024,111662,0,Cash loans,M,N,Y,0,135000.0,254700.0,30357.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
10025,111663,0,Cash loans,M,Y,Y,0,202500.0,835380.0,40320.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10026,111666,0,Cash loans,M,Y,Y,0,135000.0,1291500.0,46521.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
10027,111667,0,Cash loans,F,N,Y,0,162000.0,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
10028,111668,1,Cash loans,F,Y,Y,0,135000.0,787131.0,42066.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
10029,111670,0,Revolving loans,F,Y,Y,2,180000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10030,111671,1,Cash loans,F,N,N,0,180000.0,808650.0,31333.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10031,111672,0,Cash loans,F,N,Y,0,135000.0,307557.0,16231.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
10032,111674,0,Cash loans,M,Y,Y,0,67500.0,518562.0,20695.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
10033,111675,0,Cash loans,M,Y,Y,2,90000.0,90000.0,9823.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
10034,111676,0,Cash loans,M,Y,Y,0,126000.0,1125000.0,41692.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10035,111677,0,Cash loans,M,N,Y,1,270000.0,634482.0,20596.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,3.0
10036,111678,0,Cash loans,F,N,N,0,247500.0,508495.5,20164.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10037,111679,0,Cash loans,F,N,N,2,45000.0,71955.0,7879.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
10038,111680,0,Cash loans,F,N,Y,0,225000.0,592560.0,25236.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10039,111681,0,Cash loans,F,N,Y,0,225000.0,728460.0,44563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10040,111682,0,Cash loans,F,Y,Y,0,180000.0,1006920.0,42790.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
10041,111683,0,Cash loans,F,Y,Y,1,175500.0,547344.0,30690.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
10042,111684,0,Revolving loans,F,N,Y,0,121500.0,315000.0,15750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10043,111685,0,Cash loans,F,Y,Y,2,157500.0,900000.0,46084.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10044,111686,0,Cash loans,F,N,N,1,112500.0,675000.0,28507.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
10045,111690,1,Cash loans,F,N,Y,0,135000.0,895500.0,45720.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10046,111691,0,Cash loans,M,Y,Y,0,135000.0,945000.0,27760.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
10047,111692,0,Cash loans,F,N,Y,0,247500.0,348264.0,19575.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,0.0
10048,111693,0,Cash loans,F,N,Y,0,202500.0,592560.0,32274.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
10049,111696,0,Revolving loans,F,Y,N,0,360000.0,900000.0,45000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
10050,111697,0,Cash loans,M,N,Y,0,180000.0,942300.0,34749.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子